"""Tests for waypoint_server.py FastAPI backend."""
import pytest
import yaml
from fastapi.testclient import TestClient


SAMPLE_CONFIG = """\
waypoints:
  wp_a:
    x: 100.0
    y: 200.0
    z: 300.0
    rx: 0.0
    ry: 0.0
    rz: 90.0
    frame: robot_local
    move_type: MoveJ
    source: grasshopper
  wp_b:
    x: 400.0
    y: 0.0
    z: 500.0
    rx: 0.0
    ry: 0.0
    rz: 0.0
    frame: robot_local
    move_type: MoveL
    source: grasshopper
  home:
    joints: [0, 0, 0, 0, 0, 0, 0]
    source: human

# ── Edges (auto-generated by amalgamate_waypoints.py) ──────────────────
edges:
  - from: wp_a
    to:   wp_b
    tested: null
"""


@pytest.fixture
def config_file(tmp_path):
    p = tmp_path / "path_config.yaml"
    p.write_text(SAMPLE_CONFIG)
    return p


@pytest.fixture
def client(config_file, monkeypatch):
    import robodk_code.waypoint_server as srv
    monkeypatch.setattr(srv, "CONFIG_PATH", config_file)
    return TestClient(srv.app)


def test_get_waypoints_returns_list(client):
    r = client.get("/api/waypoints")
    assert r.status_code == 200
    data = r.json()
    assert isinstance(data, list)
    assert len(data) == 3  # wp_a, wp_b, home


def test_get_waypoints_includes_name(client):
    r = client.get("/api/waypoints")
    names = [w["name"] for w in r.json()]
    assert "wp_a" in names
    assert "wp_b" in names
    assert "home" in names


def test_get_edges_returns_list(client):
    r = client.get("/api/edges")
    assert r.status_code == 200
    data = r.json()
    assert len(data) == 1
    assert data[0]["from"] == "wp_a"
    assert data[0]["to"] == "wp_b"


def test_create_edge_adds_bidirectional(client, config_file):
    r = client.post("/api/edges", json={"from_name": "wp_b", "to_name": "home"})
    assert r.status_code == 200
    result = r.json()
    assert len(result["added"]) == 2

    edges = client.get("/api/edges").json()
    pairs = {(e["from"], e["to"]) for e in edges}
    assert ("wp_b", "home") in pairs
    assert ("home", "wp_b") in pairs


def test_create_edge_no_duplicate(client):
    # wp_a → wp_b already exists
    r = client.post("/api/edges", json={"from_name": "wp_a", "to_name": "wp_b"})
    assert r.status_code == 200
    result = r.json()
    # only wp_b → wp_a should be new
    assert len(result["added"]) == 1

    edges = client.get("/api/edges").json()
    a_to_b = [e for e in edges if e["from"] == "wp_a" and e["to"] == "wp_b"]
    assert len(a_to_b) == 1  # not duplicated


def test_delete_edge(client):
    r = client.request(
        "DELETE", "/api/edges",
        json={"from_name": "wp_a", "to_name": "wp_b"}
    )
    assert r.status_code == 200
    edges = client.get("/api/edges").json()
    assert not any(e["from"] == "wp_a" and e["to"] == "wp_b" for e in edges)
