"""
amalgamate_waypoints.py

Reads waypoint YAML source files and merges everything into path_config.yaml —
the single source of truth for all waypoints and edges.

Source files are listed in robo_dk_output/waypoint_sources.json ("sources" key).

Usage:
    python robodk_code/amalgamate_waypoints.py

To add a new YAML source, edit waypoint_sources.json:
    "sources": [
        "robo_dk_output/base_cone_waypoints.yaml",
        "robo_dk_output/machine_cone_waypoints.yaml",
        "robo_dk_output/my_new_waypoints.yaml"
    ]
"""

import os
import json
import sys

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SOURCES_CONFIG_PATH = os.path.join(REPO_ROOT, "robo_dk_output", "waypoint_sources.json")
PATH_CONFIG_PATH = os.path.join(REPO_ROOT, "robo_dk_output", "path_config.yaml")

try:
    import yaml
except ImportError:
    print("PyYAML not found. Install with: pip install pyyaml")
    sys.exit(1)


def main():
    if not os.path.exists(SOURCES_CONFIG_PATH):
        print(f"[ERROR] Config not found: {SOURCES_CONFIG_PATH}")
        sys.exit(1)

    with open(SOURCES_CONFIG_PATH, "r", encoding="utf-8") as f:
        config = json.load(f)

    sources = config.get("sources", [])

    all_waypoints = []
    all_edges = []
    seen_names = set()
    seen_edges = set()

    for src_rel in sources:
        src_path = os.path.join(REPO_ROOT, src_rel.replace("/", os.sep))
        if not os.path.exists(src_path):
            print(f"[WARN] Source not found, skipping: {src_path}")
            continue
        with open(src_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if not data:
            print(f"[WARN] Empty YAML, skipping: {src_path}")
            continue

        wps = data.get("waypoints") or []
        edges = data.get("edges") or []

        added_wp = 0
        for wp in wps:
            name = wp.get("name", "")
            if name in seen_names:
                print(f"[WARN] Duplicate waypoint '{name}' from {src_rel}, skipping")
                continue
            seen_names.add(name)
            all_waypoints.append(wp)
            added_wp += 1

        added_edge = 0
        for e in edges:
            key = (e.get("from", ""), e.get("to", ""))
            if key in seen_edges:
                continue
            seen_edges.add(key)
            all_edges.append(e)
            added_edge += 1

        print(f"[OK] {src_rel}: {added_wp} waypoints, {added_edge} edges")

    # Pull any Cartesian waypoints the user manually added to path_config.yaml
    # (joints-only entries like home/transport are skipped — no pose to visualise)
    if os.path.exists(PATH_CONFIG_PATH):
        with open(PATH_CONFIG_PATH, "r", encoding="utf-8") as f:
            pc = yaml.safe_load(f)
        pc_wps = (pc or {}).get("waypoints") or {}
        added_from_pc = 0
        for name, attrs in pc_wps.items():
            if name in seen_names or not isinstance(attrs, dict):
                continue
            if "x" not in attrs and "y" not in attrs and "z" not in attrs:
                continue
            wp = {"name": name}
            for k in ("x", "y", "z", "rx", "ry", "rz", "frame", "move_type", "j7", "source"):
                if k in attrs:
                    wp[k] = attrs[k]
            wp.setdefault("source", "human")
            seen_names.add(name)
            all_waypoints.append(wp)
            added_from_pc += 1
        if added_from_pc:
            print(f"[OK] path_config.yaml: {added_from_pc} human Cartesian waypoints")

    print(f"\n[OK] Collected {len(all_waypoints)} waypoints, {len(all_edges)} edges")
    _update_path_config(all_waypoints, all_edges)


# Marker used to find/replace the auto-generated edges block in path_config.yaml
_EDGES_MARKER = "# ── Edges (auto-generated by amalgamate_waypoints.py) ──────────────────\n"


def _update_path_config(waypoints, edges):
    """Write Cartesian waypoints and edges into path_config.yaml.

    Waypoints: only those with x/y/z. Inserted before `routing_candidates:`.
    Edges: entire edges block is replaced at the end of the file under a marker
    comment so it is easy to find and update on subsequent runs.
    """
    if not os.path.exists(PATH_CONFIG_PATH):
        print(f"[WARN] path_config.yaml not found, skipping: {PATH_CONFIG_PATH}")
        return

    with open(PATH_CONFIG_PATH, "r", encoding="utf-8") as f:
        text = f.read()
    existing = yaml.safe_load(text) or {}
    existing_names = set((existing.get("waypoints") or {}).keys())

    # ── Waypoints ─────────────────────────────────────────────────────────────
    to_add = [wp for wp in waypoints if "x" in wp and wp["name"] not in existing_names]
    if to_add:
        new_lines = []
        for wp in to_add:
            new_lines.append(f"  {wp['name']}:")
            for key in ("x", "y", "z", "rx", "ry", "rz"):
                new_lines.append(f"    {key}: {wp.get(key, 0.0)}")
            new_lines.append(f"    frame: {wp.get('frame', 'robot_local')}")
            new_lines.append(f"    move_type: {wp.get('move_type', 'MoveJ')}")
            j7 = wp.get("j7")
            new_lines.append(f"    j7: {'null' if j7 is None else j7}")
            new_lines.append(f"    source: {wp.get('source', 'grasshopper')}")
            if wp.get("z_axis_free"):
                new_lines.append(f"    z_axis_free: true")

        insert_block = "\n".join(new_lines) + "\n"
        marker = "routing_candidates:"
        idx = text.find(marker)
        text = (text[:idx] + insert_block + text[idx:]) if idx != -1 else (text.rstrip("\n") + "\n" + insert_block)
        print(f"[OK] path_config.yaml: added {len(to_add)} Cartesian waypoints")
    else:
        print("[OK] path_config.yaml: no new Cartesian waypoints to add")

    # ── Edges ─────────────────────────────────────────────────────────────────
    # Merge existing (in-file) edges with newly collected ones, dedup by (from, to)
    existing_edges = existing.get("edges") or []
    existing_edge_keys = {(e.get("from", ""), e.get("to", "")) for e in existing_edges}
    merged_edges = list(existing_edges)
    for e in edges:
        key = (e.get("from", ""), e.get("to", ""))
        if key not in existing_edge_keys:
            existing_edge_keys.add(key)
            merged_edges.append(e)

    edge_lines = [_EDGES_MARKER + "edges:"]
    for e in merged_edges:
        edge_lines.append(f"  - from: {e['from']}")
        edge_lines.append(f"    to:   {e['to']}")
        tested = e.get("tested")
        edge_lines.append(f"    tested: {'null' if tested is None else tested}")
    edges_block = "\n".join(edge_lines) + "\n"

    # Replace existing edges block or append at end
    marker_idx = text.find(_EDGES_MARKER)
    if marker_idx != -1:
        text = text[:marker_idx] + edges_block
    else:
        text = text.rstrip("\n") + "\n\n" + edges_block

    with open(PATH_CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[OK] path_config.yaml: {len(merged_edges)} edges written")


if __name__ == "__main__":
    main()
