"""
delete_waypoints.py

Remove named waypoints (and any edges that reference them) from path_config.yaml.

Usage:
    # Delete specific named waypoints
    python robodk_code/delete_waypoints.py --names home transport my_waypoint_name

    # Delete all waypoints with a given source tag
    python robodk_code/delete_waypoints.py --source human

    # Dry-run: print what would be deleted without writing
    python robodk_code/delete_waypoints.py --source human --dry-run
"""

import argparse
import os
import re
import sys

import yaml

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
CONFIG_PATH = os.path.join(REPO_ROOT, "robo_dk_output", "path_config.yaml")

_EDGES_MARKER = "# ── Edges (auto-generated by amalgamate_waypoints.py) ──────────────────\n"


def _load_text():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return f.read()


def _parse(text):
    return yaml.safe_load(text) or {}


def _delete_waypoint_block(text, name):
    """Remove a single waypoint block (2-space-indented key + 4-space body) from text."""
    pattern = rf'\n  {re.escape(name)}:\n(?:    [^\n]*\n)*'
    return re.sub(pattern, '\n', text)


def _write_edges(text, edges):
    """Rewrite the edges block (marker-delimited) in text."""
    lines = [_EDGES_MARKER + "edges:"]
    for e in edges:
        tested = e.get("tested")
        lines.append(f"  - from: {e['from']}")
        lines.append(f"    to:   {e['to']}")
        lines.append(f"    tested: {'null' if tested is None else str(tested).lower()}")
    block = "\n".join(lines) + "\n"
    idx = text.find(_EDGES_MARKER)
    return (text[:idx] + block) if idx != -1 else (text.rstrip("\n") + "\n\n" + block)


def resolve_names(data, args):
    """Return the set of waypoint names to delete."""
    wps = data.get("waypoints") or {}
    if not isinstance(wps, dict):
        return set()

    if args.names:
        missing = [n for n in args.names if n not in wps]
        if missing:
            print(f"[WARN] Not found in waypoints: {missing}")
        return set(args.names) & set(wps)

    if args.source:
        return {
            name for name, attrs in wps.items()
            if isinstance(attrs, dict) and attrs.get("source") == args.source
        }

    return set()


def main():
    parser = argparse.ArgumentParser(description="Delete waypoints from path_config.yaml")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--names", nargs="+", metavar="NAME",
                       help="Specific waypoint names to delete")
    group.add_argument("--source", metavar="SOURCE",
                       help="Delete all waypoints with this source tag (e.g. human, grasshopper)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be deleted without writing")
    args = parser.parse_args()

    text = _load_text()
    data = _parse(text)

    names_to_delete = resolve_names(data, args)
    if not names_to_delete:
        print("Nothing to delete.")
        return

    print(f"Deleting {len(names_to_delete)} waypoint(s): {sorted(names_to_delete)}")

    if args.dry_run:
        print("[dry-run] No changes written.")
        return

    # Remove waypoint blocks from text
    for name in names_to_delete:
        text = _delete_waypoint_block(text, name)

    # Remove edges that reference any deleted waypoint
    all_edges = data.get("edges") or []
    kept_edges = [
        e for e in all_edges
        if e.get("from") not in names_to_delete and e.get("to") not in names_to_delete
    ]
    removed_edge_count = len(all_edges) - len(kept_edges)
    if removed_edge_count:
        print(f"Removing {removed_edge_count} edge(s) referencing deleted waypoints.")
    text = _write_edges(text, kept_edges)

    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"[OK] Written to {CONFIG_PATH}")


if __name__ == "__main__":
    main()
