"""
state.py

Stripped-down port of DHR's knitwear-cell/src/main/robot/state.py.
Removed: @autowired DI, Redis, OPC-UA, gRPC, loguru, Configuration, RobotDriver.

State subclasses are generated by yaml_to_state_class.xq from a YAML config.
The XQuery imports from this module (and from dhr_robot).
"""
from abc import ABC
from typing import Any, List, Optional

from pydantic import BaseModel


class State(BaseModel, ABC):
    """Base class for robot operation states."""

    class MoveAbsoluteJoints(BaseModel):
        """Explicit joint targets th1-th7. None means 'keep current value'."""
        th1: Optional[float] = None
        th2: Optional[float] = None
        th3: Optional[float] = None
        th4: Optional[float] = None
        th5: Optional[float] = None
        th6: Optional[float] = None
        th7: Optional[float] = None

    class Parameters(BaseModel):
        """Runtime parameters injected into a state at execution time."""
        mechanisms: Optional[List[str]] = None
        target_joints: Optional[List[float]] = None
        targets: Optional[List[str]] = None
        speed_joints: Optional[float] = None
        accel_joints: Optional[float] = None
        rotate: Optional[str] = None

    # Robot controller — set by generated state classes via Field(default_factory)
    robot_controller: Any = None  # dhr_robot.Robot instance

    # Common movement fields (mirror DHR's State)
    robot: Optional[str] = None
    blocking: Optional[bool] = True
    tool_name: Optional[str] = None
    frame: Optional[str] = None
    target: Optional[str] = None
    speed_joints: float = 5000
    move_absolute_joints: Optional[MoveAbsoluteJoints] = None
    parameters: Optional[Parameters] = None
    optimization_frame: Optional[str] = None
    optimization_axis: Optional[str] = None

    def handle(self) -> bool:
        """Execute this state through its robot_controller. Returns True on success."""
        return self.robot_controller.execute(self)

    class Config:
        arbitrary_types_allowed = True
