"""
waypoint_server.py

FastAPI backend for the waypoint 3D viewer.

Run (WSL, robodk_v1 env):
    uvicorn robodk_code.waypoint_server:app --host 0.0.0.0 --port 8000 --reload

Open from Windows: http://localhost:8000  (WSL2 port-forwards automatically)
During dev, the Vite dev server runs separately on port 5173 and proxies /api to here.
"""
from pathlib import Path

import yaml
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

app = FastAPI(title="Waypoint Viewer")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

REPO_ROOT = Path(__file__).parent.parent
CONFIG_PATH = REPO_ROOT / "robo_dk_output" / "path_config.yaml"
_EDGES_MARKER = "# ── Edges (auto-generated by amalgamate_waypoints.py) ──────────────────\n"


def _load() -> dict:
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _read_text() -> str:
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return f.read()


def _write_edges(text: str, edges: list) -> None:
    lines = [_EDGES_MARKER + "edges:"]
    for e in edges:
        lines.append(f"  - from: {e['from']}")
        lines.append(f"    to:   {e['to']}")
        tested = e.get("tested")
        lines.append(f"    tested: {'null' if tested is None else tested}")
    block = "\n".join(lines) + "\n"
    idx = text.find(_EDGES_MARKER)
    text = (text[:idx] + block) if idx != -1 else (text.rstrip("\n") + "\n\n" + block)
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write(text)


@app.get("/api/waypoints")
def get_waypoints():
    raw = _load().get("waypoints") or {}
    return [{"name": k, **v} for k, v in raw.items() if isinstance(v, dict)]


@app.get("/api/edges")
def get_edges():
    return _load().get("edges") or []


class EdgeRequest(BaseModel):
    from_name: str
    to_name: str


@app.post("/api/edges")
def create_edge(req: EdgeRequest):
    text = _read_text()
    edges = list(_load().get("edges") or [])
    existing = {(e.get("from", ""), e.get("to", "")) for e in edges}
    added = []
    for frm, to in [(req.from_name, req.to_name), (req.to_name, req.from_name)]:
        if (frm, to) not in existing:
            edges.append({"from": frm, "to": to, "tested": None})
            added.append(f"{frm} -> {to}")
    _write_edges(text, edges)
    return {"added": added}


@app.delete("/api/edges")
def delete_edge(req: EdgeRequest):
    text = _read_text()
    edges = [
        e for e in (_load().get("edges") or [])
        if not (e.get("from") == req.from_name and e.get("to") == req.to_name)
    ]
    _write_edges(text, edges)
    return {"deleted": f"{req.from_name} -> {req.to_name}"}


# Serve built frontend in production
_dist = REPO_ROOT / "waypoint_viewer" / "dist"
if _dist.exists():
    app.mount("/", StaticFiles(directory=str(_dist), html=True), name="frontend")
